version: '3.8'

services:
  # # Production build
  # web:
  #   container_name: perspective-lifestyle-web
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:80"
  #   restart: unless-stopped
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
  #     interval: 30s
  #     timeout: 3s
  #     start_period: 5s
  #     retries: 3

  # Development environment (optional - comment out if not needed)
  dev:
    container_name: perspective-lifestyle-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5175:5173"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

